import type { Metadata } from "next";
import { Outfit, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/navigation/Sidebar";
import Link from "next/link";

import MobileHeader from "@/components/navigation/MobileHeader";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

const ibmPlexMono = IBM_Plex_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "InvestorGPT — Autonomous Multi-Agent Investment Research Platform",
  description: "Get institutional-grade, fully verified, and explainable stock research reports generated by collaborative AI agent committees.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${ibmPlexMono.variable} h-full antialiased dark`}
      style={{ colorScheme: "dark" }}
    >
      <body className="min-h-full flex font-sans selection:bg-accent selection:text-white bg-[#060709] text-foreground">
        <Sidebar />
        <div className="flex-1 flex flex-col min-h-screen overflow-y-auto w-full">
          <MobileHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
